server:
  port: 8762
  
spring:
  application:
    name: eureka-server
  security:   #安全保护，需要用户输入用户名和密码
    user:
      name: admin
      password: admin  
      
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true   #注册到eureka
    fetch-registry: true         #从注册中心获取服务列表
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  server:
    enable-self-preservation: true   #true开启自我保护模式，
    eviction-interval-timer-in-ms: 60000 #清理时间间隔，单位毫秒，默认60秒         